# Generated by Django 5.1.7 on 2025-04-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
